"use client";
import React from "react";
import Footer from "../components/footer";
import Header from "../components/header";

const TermsOfService = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <div className="relative h-screen flex flex-col justify-center items-center w-full overflow-hidden">
        <Header />

        <img
          src="/terms.jpg"
          className="absolute top-0 left-0 w-full h-full object-cover z-0"
          alt=""
        />
        {/* Content Section */}
        <div className="relative bg-black opacity-80 z-10 w-full h-screen"></div>

        <div className="absolute z-20 h-full flex items-center">
          <div className="container mx-auto px-4 md:px-8 lg:px-12">
            <div className="px-4 md:px-12 lg:px-24 flex flex-col gap-6 md:gap-10">
              <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-7xl text-white font-semibold mb-4 md:mb-6">
                Terms of Service
              </h1>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-white text-black py-12 sm:py-16 md:py-20 lg:py-28 px-4 sm:px-8 md:px-16 lg:px-24 xl:px-54">
        <div className="flex flex-col gap-10 sm:gap-12 md:gap-16 lg:gap-20 max-w-7xl mx-auto">
          <div className="flex flex-col gap-4 sm:gap-6">
            <p className="text-base sm:text-lg">
              THIS TERMS OF SERVICE AGREEMENT ("THIS AGREEMENT" OR "THESE
              TERMS") IS A LEGAL AGREEMENT BETWEEN YOU, ON THE ONE HAND, AND
              Lagree Eliteform FITNESS LTD., Lagree Eliteform FITNESS VICTORIA
              LTD, AND EACH OF THEIR RESPECTIVE SUBSIDIARIES AND AFFILIATES
              (COLLECTIVELY, "Lagree Eliteform," "THE COMPANY", "US," OR "WE"),
              ON THE OTHER HAND, REGARDING YOUR USE OF SERVICES (INCLUDING
              PARTICIPATING IN ANY CLASSES, SESSIONS, EVENTS OR ACTIVITIES
              HOSTED, SPONSORED, OR AFFILIATED WITH Lagree Eliteform,
              COLLECTIVELY, THE "PROGRAM") WHETHER AT OR VIA : (I) A Lagree
              Eliteform IN-PERSON LOCATION; (II) HTTPS://WWW.LAGREEWEST.COM/
              (THE "WEBSITE"); AND/OR (III) ANY APP OR OTHER SOFTWARE PROVIDED
              BY Lagree Eliteform (COLLECTIVELY, THE "SERVICE").
            </p>
            <p className="text-base sm:text-lg">
              BY CLICKING "I AGREE", "I ACCEPT", "SUBMIT ORDER & RESERVE CLASS",
              OR SIMILAR LANGUAGE, YOU AGREE TO BE BOUND IN ALL RESPECTS BY THIS
              AGREEMENT, AND YOU WILL WAIVE CERTAIN LEGAL RIGHTS, INCLUDING THE
              RIGHT TO SUE OR CLAIM COMPENSATION, AS SET FORTH BELOW.
            </p>
          </div>

          <div className="flex flex-col gap-4 sm:gap-6">
            <p className="text-2xl sm:text-3xl md:text-4xl font-bold">
              PART 1: RELEASE OF LIABILITY, WAIVER OF CLAIMS AND ASSUMPTION OF
              RISKS
            </p>
            <p className="text-lg sm:text-xl font-medium">
              PLEASE READ CAREFULLY
            </p>
            <p className="text-base sm:text-lg">
              IN CONSIDERATION OF Lagree Eliteform PERMITTING YOU ("I" OR "ME")
              TO PARTICIPATE IN ACTIVITIES INCLUDING (BUT NOT LIMITED TO) LAGREE
              CLASSES, MEGAFORMER CLASSES, MAT CLASSES, REFORMER CLASSES, AND
              OTHER EXERCISE OR PERSONAL TRAINING SESSIONS (INCLUDING PRIVATE
              SESSIONS FOR INDIVIDUALS OR GROUPS) AND THE USE OF Lagree
              Eliteform'S OTHER ON-SITE AMENITIES (COLLECTIVELY, THE
              "ACTIVITIES"), AND FOR OTHER GOOD AND VALUABLE CONSIDERATION, YOU
              AGREE TO ALL THE TERMS AND CONDITIONS SET FORTH IN THIS AGREEMENT
              (THIS "AGREEMENT").
            </p>
          </div>

          <div className="flex flex-col gap-6">
            <p className="text-4xl font-bold">ASSUMPTION OF RISKS</p>

            <p className="text-xl font-medium">1. RISKS ACKNOWLEDGMENT</p>
            <p className="font-light">
              I AM AWARE AND UNDERSTAND THAT THE ACTIVITIES MAY INVOLVE MANY
              RISKS, DANGERS AND HAZARDS, INCLUDING BUT NOT LIMITED TO THE RISK
              OF SERIOUS INJURY, DEATH OR PROPERTY DAMAGE. I ACKNOWLEDGE THAT I
              AM VOLUNTARILY PARTICIPATING IN THE ACTIVITIES. I FREELY ACCEPT
              AND FULLY ASSUME ANY AND ALL OF THE RISKS, DANGERS AND HAZARDS
              INVOLVED AND THE POSSIBILITY OF INJURY, DEATH OR PROPERTY DAMAGE,
              WHETHER CAUSED BY THE NEGLIGENCE OF Lagree Eliteform OR OTHERWISE.
              I UNDERSTAND THAT I SHOULD CONSULT A DOCTOR IN ADVANCE OF
              PERFORMING OR PARTICIPATING IN ANY OF THE ACTIVITIES AND THAT I
              SHOULD ADVISE Lagree Eliteform OF ANY HEALTH CONCERNS IN ADVANCE
              OF STARTING THE ACTIVITIES. I UNDERSTAND THAT CERTAIN ACTIVITIES
              MAY INVOLVE LIMITED LIGHT AND THE USE OF VARIOUS EXERCISE
              MACHINES. LAGREE WEST DOES NOT GUARANTEE THAT YOU WILL ACHIEVE
              YOUR DESIRED FITNESS RESULTS FROM PARTICIPATING IN AN ACTIVITY.
            </p>

            <p className="text-xl font-medium">2. WAIVER AND RELEASE</p>
            <p className="font-light">
              I HEREBY EXPRESSLY WAIVE AND RELEASE ANY AND ALL CLAIMS WHICH I
              HAVE OR MAY IN THE FUTURE HAVE AGAINST ONE OR MORE OF Lagree
              Eliteform, ANY ENTITIES (INCLUDING, WITHOUT LIMITATION, COMPANIES,
              PARTNERSHIPS, AND TRUSTS) OWNED, IN WHOLE OR IN PART, BY LAGREE
              WEST, AND EACH OF THEIR AFFILIATES AND EACH OF THEIR RESPECTIVE
              DIRECTORS, MANAGERS, OFFICERS, EMPLOYEES, CONTRACTORS, AGENTS,
              REPRESENTATIVES, SHAREHOLDERS, SUCCESSORS AND ASSIGNS
              (COLLECTIVELY, THE "RELEASEES"), ARISING OUT OF OR RELATED TO ANY
              OF THE ACTIVITIES (INCLUDING WHILE ON MY WAY TO, WHILE AT, AND
              WHILE LEAVING ANY PREMISES AT WHICH Lagree Eliteform OFFERS ANY OF
              THE ACTIVITIES), THE PROGRAM AND/OR THE SERVICE DUE TO ANY CAUSE
              WHATSOEVER, INCLUDING, WITHOUT LIMITATION, THE NEGLIGENCE OF
              Lagree Eliteform OR ANY OTHER RELEASEE, BREACH OF CONTRACT, OR
              BREACH OF ANY STATUTORY OR OTHER DUTY OF CARE OWING UNDER
              OCCUPIERS LIABILITY LEGISLATION OR OTHERWISE.
            </p>

            <p className="text-xl font-medium">3. COVENANT NOT TO SUE</p>
            <p className="font-light">
              I COVENANT NOT TO MAKE OR BRING ANY SUCH CLAIM AGAINST Lagree
              Eliteform OR ANY OTHER RELEASEE, AND FOREVER RELEASE AND DISCHARGE
              LAGREE WEST AND ALL OTHER RELEASEES FROM ANY LIABILITY WHATSOEVER
              UNDER SUCH CLAIMS. I SHALL INDEMNIFY, DEFEND, AND HOLD Lagree
              Eliteform AND ALL OTHER RELEASEES HARMLESS AGAINST ANY AND ALL
              LOSSES, DAMAGES, LIABILITIES, DEFICIENCIES, CLAIMS, ACTIONS,
              JUDGMENTS, SETTLEMENTS, INTEREST, AWARDS, PENALTIES, FINES, COSTS,
              OR EXPENSES OF WHATEVER KIND OR NATURE WHATSOEVER, INCLUDING
              REASONABLE LEGAL FEES, INCURRED IN CONNECTION WITH ANY THIRD-PARTY
              CLAIM, SUIT, ACTION OR PROCEEDING ARISING OUT OF OR RELATED TO ANY
              OF THE ACTIVITIES (INCLUDING WHILE ON MY WAY TO, WHILE AT, AND
              WHILE LEAVING ANY PREMISES AT WHICH Lagree Eliteform OFFERS ANY OF
              THE ACTIVITIES), THE PROGRAM AND/OR THE SERVICE.
            </p>

            <p className="text-xl font-medium">4. PERSONAL PROPERTY</p>
            <p className="font-light">
              I ACCEPT THAT THE COMPANY ASSUMES NO RESPONSIBILITY WHATSOEVER,
              DIRECTLY OR INDIRECTLY, FOR ANY OF MY PERSONAL PROPERTY,
              REGARDLESS OF WHETHER SUCH PROPERTY IS LOST, STOLEN OR DAMAGED.
            </p>

            <p className="text-xl font-medium">5. LIABILITY LIMITATION</p>
            <p className="font-light">
              IF A COURT OF COMPETENT JURISDICTION DETERMINES THAT THE RELEASE
              OF CLAIMS SET FORTH HEREIN IS NOT VALID, I AGREE THAT IN NO EVENT
              SHALL THE RELEASEES' AGGREGATE LIABILITY ARISING OUT OF OR RELATED
              TO ANY OF THE ACTIVITIES, THE PROGRAM OR THE SERVICE EXCEED THE
              GREATER OF (I) THE TOTAL AMOUNT PAID BY ME TO Lagree Eliteform IN
              THE 6 MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM; AND
              (II) $500.
            </p>

            <p className="text-xl font-medium">6. ENTIRE AGREEMENT</p>
            <p className="font-light">
              THIS AGREEMENT CONSTITUTES THE ENTIRE AGREEMENT OF Lagree
              Eliteform AND ME WITH RESPECT TO THE SUBJECT MATTER CONTAINED
              HEREIN AND SUPERSEDES ALL PRIOR AND CONTEMPORANEOUS
              UNDERSTANDINGS, AGREEMENTS, REPRESENTATIONS AND WARRANTIES, BOTH
              WRITTEN AND ORAL, WITH RESPECT TO SUCH SUBJECT MATTER.
            </p>

            <p className="text-xl font-medium">7. SEVERABILITY</p>
            <p className="font-light">
              IF ANY TERM OR PROVISION OF THIS AGREEMENT IS HELD TO BE INVALID,
              ILLEGAL OR UNENFORCEABLE IN ANY JURISDICTION, SUCH INVALIDITY,
              ILLEGALITY OR UNENFORCEABILITY SHALL NOT AFFECT ANY OTHER TERM OR
              PROVISION OF THIS AGREEMENT OR INVALIDATE OR RENDER UNENFORCEABLE
              SUCH TERM OR PROVISION IN ANY OTHER JURISDICTION.
            </p>

            <p className="text-xl font-medium">8. BINDING EFFECT</p>
            <p className="font-light">
              THIS AGREEMENT IS BINDING ON AND SHALL ENURE TO THE BENEFIT OF
              Lagree Eliteform AND ME AND EACH OF OUR RESPECTIVE (AS APPLICABLE)
              HEIRS, EXECUTORS, ADMINISTRATORS, SUCCESSORS, AND PERMITTED
              ASSIGNS.
            </p>

            <p className="text-xl font-medium">9. GOVERNING LAW</p>
            <p className="font-light">
              THIS AGREEMENT SHALL BE INTERPRETED AND CONSTRUED IN ACCORDANCE
              WITH THE LAWS OF THE PROVINCE OF BRITISH COLUMBIA AND THE FEDERAL
              LAWS OF CANADA APPLICABLE THEREIN; AND TO THE EXTENT PERMITTED BY
              APPLICABLE LAW, ANY CLAIM OR CAUSE OF ACTION ARISING UNDER THIS
              AGREEMENT MAY BE BROUGHT ONLY IN THE COURTS OF THE PROVINCE OF
              BRITISH COLUMBIA, AND I HEREBY CONSENT TO THE EXCLUSIVE
              JURISDICTION OF SUCH COURTS; PROVIDED THAT (I) I SHALL BE
              PERMITTED TO BRING A CLAIM IN THE COURTS OF THE PROVINCE OF
              ONTARIO WITH RESPECT TO ANY ACTIVITY IN ONTARIO; AND (II) TO THE
              EXTENT THAT APPLICABLE CONSUMER PROTECTION LAWS OF ANY
              JURISDICTION PERMIT ME TO BRING A CLAIM IN SUCH OTHER
              JURISDICTION, THEN THIS AGREEMENT SHALL NOT PROHIBIT ME FROM
              BRINGING A CLAIM IN SUCH JURISDICTION.
            </p>

            <p className="text-xl font-medium">10. LANGUAGE</p>
            <p className="font-light">
              THE PARTIES HERETO HAVE REQUIRED THAT THIS AGREEMENT AND ALL
              DOCUMENTS AND NOTICES RESULTING FROM IT BE DRAWN UP IN ENGLISH.
              LES PARTIES AUX PRÉSENTS ONT EXIGÉS QUE LA PRÉSENTE CONVENTION
              AINSI QUE TOUS LES DOCUMENTS ET AVIS QUI S'Y RATTACHENT OU QUI EN
              DÉCOULERONT SOIT RÉDIGÉS EN LA LANGUE ANGLAISE. Lagree Eliteform
              RECEIVES THE BENEFIT OF THIS AGREEMENT ON BEHALF OF THE OTHER
              RELEASEES, AS TRUSTEE AND AGENT FOR SUCH RELEASEES, AND LAGREE
              WEST SHALL BE ENTITLED TO ENFORCE THIS AGREEMENT ON BEHALF OF EACH
              OF THE OTHER RELEASEES.
            </p>

            <p className="text-xl font-medium">11. AUTHORITY TO BIND</p>
            <p className="font-light">
              WITHOUT LIMITING ANY OF THE FOREGOING, I AGREE THAT IF I AM
              ENGAGING IN OR IF I ENGAGE IN THE ANY ACTIVITIES, THE PROGRAM
              AND/OR THE SERVICE IN MY CAPACITY AS AN EMPLOYEE, AGENT, DIRECTOR,
              OFFICER, OR OTHER REPRESENTATIVE OF ANY ENTITY (INCLUDING, WITHOUT
              LIMITATION, A COMPANY, PARTNERSHIP, OR TRUST), I AGREE THAT I AM
              AUTHORIZED TO BIND SUCH ENTITY, AND THAT, BY ENTERING INTO THIS
              AGREEMENT, I ALSO AGREE THAT THIS AGREEMENT SHALL ALSO BE DEEMED
              TO APPLY TO ANY CLAIMS THAT SUCH ENTITY MAY HAVE ARISING FROM OR
              RELATING TO THE ACTIVITIES AND SHALL FUNCTION AS A RELEASE FROM
              BOTH (I) ME IN MY INDIVIDUAL CAPACITY; AND (II) SUCH ENTITY.
            </p>

            <p className="text-xl font-medium">12. ACKNOWLEDGEMENT</p>
            <p className="font-light">
              I ACKNOWLEDGE THAT I HAVE READ AND UNDERSTOOD ALL OF THE TERMS OF
              THIS AGREEMENT AND THAT I AM VOLUNTARILY WAIVING SUBSTANTIAL LEGAL
              RIGHTS, INCLUDING THE RIGHT TO SUE Lagree Eliteform AND THE
              RELEASEES.
            </p>
          </div>

          <div className="flex flex-col gap-6">
            <p className="text-4xl font-bold">PART 2: ADDITIONAL TERMS</p>

            <p className="text-xl font-medium">ELIGIBILITY</p>
            <p className="font-light">
              YOU MUST BE 16 YEARS OF AGE OR OLDER TO USE Lagree Eliteform'S
              PROGRAM & SERVICE.
            </p>
            <p className="font-light">
              IF YOU ARE BELOW THE AGE OF MAJORITY TO ENTER INTO A CONTRACT
              WITHOUT THE CONSENT OF YOUR PARENT OR LEGAL GUARDIAN (E.G. UNDER
              19 IN BRITISH COLUMBIA OR UNDER 18 IN ONTARIO), THEN YOU
              REPRESENT, WARRANT, ACKNOWLEDGE, AND AGREE THAT (I) YOU ARE ‎USING
              THE PROGRAM AND THE SERVICE WITH THE CONSENT OF YOUR PARENT OR
              LEGAL GUARDIAN WHO HAS AGREED TO ‎THESE TERMS AND WILL BE PRESENT
              WHILE YOU USE THE SERVICE AND PARTICIPATE IN THE PROGRAM; AND (II)
              YOU HAVE FILLED OUT ANY FORM FOR MINORS ON OUR WEBSITE. IF YOU ARE
              A PARENT OR LEGAL GUARDIAN AGREEING TO THESE TERMS FOR THE BENEFIT
              OF A ‎MINOR, YOU ARE FULLY RESPONSIBLE FOR (A) REVIEWING THESE
              TERMS WITH THE MINOR, (B) ENSURING THE ‎MINOR UNDERSTANDS THESE
              TERMS, AND (C) THE MINOR'S USE OF THE PROGRAM AND SERVICE,
              INCLUDING ALL ‎LEGAL LIABILITY THEY MAY INCUR.
            </p>

            <p className="text-xl font-medium">RESPECT</p>
            <p className="font-light">
              THREATENING LANGUAGE, HARASSMENT, VIOLENCE, RACISM, BULLYING,
              ATTACKS ON OR INTIMIDATION OF ANY PARTY, INCLUDING OUR MEMBERS OR
              STAFF; MALICIOUS SPEECH REGARDING TOPICS OF SEXUAL ORIENTATION,
              GENDER, GENDER IDENTITY, AGE, ETHNIC ORIGIN OR RACE, RELIGION,
              NATIONALITY, DISABILITY, SIZE, VETERAN STATUS, MARITAL STATUS,
              SEXIST COMMENTS; OR HATE SPEECH WILL NOT BE TOLERATED.
            </p>
            <p className="font-light">
              DISCRIMINATION AGAINST PEOPLE BASED ON RACE, ETHNICITY, RELIGION,
              DISABILITY, GENDER, GENDER IDENTITY, AGE, MARITAL STATUS,
              NATIONALITY, SEXUAL ORIENTATION, OR ANY OTHER CHARACTERISTICS
              PROTECTED UNDER APPLICABLE LAW WILL NOT BE TOLERATED.
            </p>

            <p className="text-xl font-medium">ADDITIONAL HEALTH DISCLAIMER</p>
            <p className="font-light">
              I AGREE THAT I WILL NOT PARTICIPATE IN THE PROGRAM WHILE UNDER THE
              INFLUENCE OF DRUGS OR ALCOHOL AND WILL NOT CONSUME DRUGS OR
              ALCOHOL WHILE PARTICIPATING IN THE PROGRAM.
            </p>

            <p className="text-xl font-medium">ACCOUNT</p>
            <p className="font-light">
              IN ORDER TO USE THE SERVICE, YOU MUST CREATE AN ACCOUNT. WHEN
              REGISTERING FOR AN ACCOUNT, YOU MUST PROVIDE ACCURATE AND COMPLETE
              INFORMATION AND PROMPTLY UPDATE THIS INFORMATION TO KEEP IT
              CURRENT. IF YOU PROVIDE ANY INFORMATION THAT IS INACCURATE OR
              INCOMPLETE, OR WE HAVE REASON TO BELIEVE THAT THE INFORMATION IS
              INACCURATE OR INCOMPLETE, WE MAY SUSPEND OR TERMINATE YOUR ACCOUNT
              AND YOUR USE OF THE SERVICE AND PROGRAM.
            </p>
            <p className="font-light">
              YOU ARE SOLELY RESPONSIBLE FOR ALL ACTIVITIES THAT OCCUR THROUGH
              YOUR ACCOUNT. USERS ARE RESPONSIBLE FOR KEEPING THEIR LOGIN
              CREDENTIALS CONFIDENTIAL AND SAFE. FOR THIS REASON, USERS ARE ALSO
              REQUIRED TO CHOOSE PASSWORDS THAT MEET THE HIGHEST STANDARDS OF
              STRENGTH. BY REGISTERING, USERS AGREE TO BE FULLY RESPONSIBLE FOR
              ALL ACTIVITIES THAT OCCUR UNDER THEIR USERNAME AND PASSWORD.
            </p>
            <p className="font-light">
              TO PROTECT YOUR ACCOUNT FROM UNAUTHORIZED USE, DO NOT PROVIDE YOUR
              USERNAME OR PASSWORD TO ANYONE ELSE. PLEASE NOTIFY US IMMEDIATELY
              OF ANY UNAUTHORIZED USE OF YOUR ACCOUNT OR ANY OTHER BREACH OF
              SECURITY BY SENDING AN EMAIL TO{" "}
              <a
                href="mailto:info@lagreeeliteform.com
"
                className="underline"
              >
                {" "}
                info@lagreeeliteform.com
              </a>
              .
            </p>

            <p className="text-xl font-medium">MEMBERSHIP SUBSCRIPTION FEES</p>
            <p className="font-light">
              Lagree Eliteform OFFERS MEMBERSHIP SUBSCRIPTION-BASED ACCESS TO
              ITS IN-PERSON PROGRAM. Lagree Eliteform RESERVES THE RIGHT TO
              CANCEL, INTERRUPT, OR RESCHEDULE ANY PROGRAM.
            </p>
            <p className="font-light">
              Lagree Eliteform USES A THIRD-PARTY PAYMENT PROCESSOR (THE
              "PAYMENT PROCESSOR") TO LINK YOUR CREDIT CARD ACCOUNT TO THE
              SERVICE. THE PROCESSING OF PAYMENTS OR CREDITS, AS APPLICABLE, IN
              CONNECTION WITH YOUR USE OF THE SERVICE WILL BE SUBJECT TO THE
              TERMS, CONDITIONS AND PRIVACY POLICIES OF THE PAYMENT PROCESSOR
              AND YOUR CREDIT CARD ISSUER IN ADDITION TO THESE TERMS. Lagree
              Eliteform IS NOT RESPONSIBLE FOR ANY ERRORS BY THE PAYMENT
              PROCESSOR. IN CONNECTION WITH YOUR USE OF THE SERVICE, Lagree
              Eliteform WILL OBTAIN CERTAIN TRANSACTION DETAILS, WHICH WILL BE
              USED SOLELY IN ACCORDANCE WITH ITS PRIVACY POLICY.
            </p>
            <p className="font-light">
              MEMBERSHIPS ARE BILLED ON A PERIODIC BASIS AS SPECIFIED EITHER AT
              THE TIME OF PURCHASE OR IN THE FAQS + POLICIES ON OUR WEBSITE.
              YOUR MEMBERSHIP SUBSCRIPTION WILL CONTINUE IN EFFECT ON A
              RECURRING BASIS CORRESPONDING TO THE TERM OF YOUR SUBSCRIPTION
              UNLESS AND UNTIL YOU CANCEL YOUR SUBSCRIPTION OR THE ACCOUNT OR
              THE SERVICE IS OTHERWISE SUSPENDED OR DISCONTINUED PURSUANT TO
              THIS AGREEMENT. IF YOUR MEMBERSHIP IS CANCELLED OR TERMINATED
              BEFORE THE END OF THE APPLICABLE BILLING CYCLE, Lagree Eliteform
              WILL NOT REIMBURSE YOU FOR THE REMAINDER OF THAT BILLING CYCLE.
              MEMBERS MAY CANCEL THEIR MEMBERSHIP AT ANY TIME. MEMBERSHIP MUST
              BE CANCELED PRIOR TO THE RENEWAL DATE IN ORDER TO AVOID ADDITIONAL
              MEMBERSHIP CHARGES.
            </p>
            <p className="font-light">
              WHEN YOU PURCHASE A MEMBERSHIP SUBSCRIPTION, YOU WILL INITIALLY BE
              CHARGED AT THE RATE APPLICABLE AT THE TIME OF YOUR AGREEMENT TO
              SUBSCRIBE. IF Lagree Eliteform LATER INCREASES THE PRICE OF THE
              SUBSCRIPTION, WE WILL NOTIFY YOU VIA EMAIL. WE RESERVE THE RIGHT
              TO CHANGE THE PRICE OF OUR SUBSCRIPTION AT ANY TIME IN ACCORDANCE
              WITH OUR FAQS + POLICIES (AS DEFINED BELOW)
            </p>
            <p className="font-light">
              WITH RESPECT TO ANY FREE TRIALS THAT WE MAY OFFER: WE REQUIRE THAT
              YOU PROVIDE A VALID CREDIT OR DEBIT CARD AT THE TIME YOU REGISTER
              FOR A FREE TRIAL TO ENSURE THAT YOU HAVE CONTINUED ACCESS TO YOUR
              MEMBERSHIP AFTER THE EXPIRATION OF THE FREE TRIAL PERIOD. LAGREE
              WEST WILL NOT BILL YOUR ACCOUNT UNTIL THE FREE TRIAL HAS EXPIRED
              AND PROVIDED THAT YOU HAVE NOT CANCELLED YOUR ACCOUNT DURING THE
              FREE TRIAL PERIOD. YOU MAY ONLY USE A FREE TRIAL ONCE. IT IS VERY
              IMPORTANT TO UNDERSTAND THAT YOU WILL NOT RECEIVE A NOTICE FROM
              Lagree Eliteform THAT YOUR FREE TRIAL HAS ENDED AND THAT PAYMENT
              FOR YOUR SUBSCRIPTION IS DUE. IF YOU WISH TO AVOID CHARGES TO YOUR
              PAYMENT METHOD, YOU MUST CANCEL YOUR SUBSCRIPTION PRIOR TO
              MIDNIGHT PST ON THE LAST DAY OF YOUR FREE TRIAL PERIOD.
            </p>
            <p className="font-light">
              USERS MAY NOT SHARE, GIVE OR SELL THEIR PASSWORD OR USERNAME TO
              ANY OTHER PERSON OR ENTITY. EXCESSIVE VIEWINGS OR LOGINS BY ANY
              USER WILL BE CONSTRUED BY Lagree Eliteform AS FRAUDULENT USE,
              WHICH WILL RESULT IN THE IMMEDIATE CANCELLATION OF MEMBERSHIP
              WITHOUT REFUND. WE RESERVE THE RIGHT TO CANCEL ANY MEMBERSHIP
              WHICH WE BELIEVE HAS BEEN COMPROMISED, OR IS BEING USED
              FRAUDULENTLY, AT OUR OWN DISCRETION.
            </p>

            <p className="text-xl font-medium">ADDITIONAL FAQS + POLICIES</p>
            <p className="font-light">
              THE FAQS + POLICIES ON OUR WEBSITE
              (HTTPS://WWW.LAGREEWEST.COM/FAQ-POLICIES OR OTHERWISE DISCLOSED TO
              YOU FROM TIME TO TIME IN WRITING (THE "FAQS + POLICIES") SHALL BE
              DEEMED TO BE INCORPORATED BY REFERENCE INTO THESE TERMS. WE
              RESERVE THE RIGHT TO AMEND THE FAQS + POLICIES IN GOOD FAITH FROM
              TIME TO TIME, AND SUCH AMENDMENTS SHALL BE APPLICABLE TO ANY
              SUBSEQUENT PROGRAM OR SERVICE IN WHICH YOU PARTICIPATE (INCLUDING
              A PROGRAM FOR WHICH YOU HAVE ALREADY PAID OR OTHERWISE
              SUBSCRIBED).
            </p>
            <p className="font-light">
              IN THE EVENT OF A CONFLICT BETWEEN THESE TERMS AND THE FAQS +
              POLICIES, THESE TERMS SHALL GOVERN.
            </p>
            <p className="font-light">
              THE FAQS + POLICIES MAY INCLUDE IMPORTANT POLICIES SUCH AS OUR
              CANCELLATION POLICY, LATE POLICY, MEMBERSHIP POLICY, AND STUDIO
              POLICY.
            </p>

            <p className="text-xl font-medium">SERVICE PROVIDER</p>
            <p className="font-light">
              IF YOU PARTICIPATE IN A PROGRAM THAT TAKES PLACE AT ONE OF LAGREE
              WEST'S IN-PERSON LOCATIONS, THEN YOU ARE CONTRACTING WITH THE
              FOLLOWING Lagree Eliteform ENTITIES:
              <br />- ANY OF OUR VANCOUVER LOCATIONS: Lagree Eliteform FITNESS
              LTD.
              <br />- ANY OF OUR VICTORIA LOCATIONS: Lagree Eliteform FITNESS
              VICTORIA LTD.
            </p>

            <p className="text-xl font-medium">OFFERS AND DISCOUNTS</p>
            <p className="font-light">
              Lagree Eliteform MAY OFFER DISCOUNTS, PROMO CODES, OR PROVIDE
              SPECIAL OFFERS FOR THE PURCHASE OF PROGRAMS OR PRODUCTS. ANY SUCH
              OFFER OR DISCOUNT SHALL ALWAYS BE SUBJECT TO THE ELIGIBILITY
              CRITERIA AND ARE ALWAYS GRANTED AT OUR SOLE DISCRETION. REPEATED
              OR RECURRING OFFERS OR DISCOUNTS CREATE NO CLAIM/TITLE OR RIGHT
              THAT USERS MAY ENFORCE IN THE FUTURE. DEPENDING ON THE CASE,
              DISCOUNTS OR OFFERS SHALL BE VALID FOR A LIMITED TIME ONLY OR IN
              LIMITED QUANTITY AND ONLY AVAILABLE TO CERTAIN PEOPLE.
            </p>

            <p className="text-xl font-medium">COUPONS AND OFFER CODES</p>
            <p className="font-light">
              OFFERS OR DISCOUNTS CAN BE BASED ON COUPONS AND OFFER CODES
              (COLLECTIVELY, "COUPONS"). UNLESS OTHERWISE STATED, THE FOLLOWING
              RULES APPLY TO THE USE OF COUPONS:
            </p>
            <p className="font-light">
              - EACH COUPON IS ONLY VALID WHEN USED IN THE MANNER AND WITHIN THE
              TIMEFRAME SPECIFIED ON THE WEBSITE AND/OR THE COUPON;
              <br />- A COUPON MAY ONLY BE APPLIED, IN ITS ENTIRETY, AT THE
              ACTUAL TIME OF PURCHASE
              <br />- UNLESS OTHERWISE STATED, SINGLE-USE COUPONS MAY ONLY BE
              USED ONCE PER PURCHASE AND THEREFORE MAY ONLY BE APPLIED A SINGLE
              TIME EVEN IN CASES INVOLVING INSTALLMENT-BASED PURCHASES; A COUPON
              CANNOT BE APPLIED CUMULATIVELY;
              <br />- A COUPON MUST BE REDEEMED EXCLUSIVELY WITHIN THE TIME
              SPECIFIED IN THE OFFER. AFTER THIS PERIOD, THE COUPON WILL
              AUTOMATICALLY EXPIRE, PRECLUDING ANY POSSIBILITY FOR THE USER TO
              CLAIM THE RELEVANT RIGHTS, INCLUDING CASH-OUT;
              <br />- THE USER IS NOT ENTITLED TO ANY CREDIT/REFUND/COMPENSATION
              IF THERE IS A DIFFERENCE BETWEEN THE VALUE OF THE COUPON AND THE
              REDEEMED VALUE;
              <br />- THE COUPON IS INTENDED SOLELY FOR NON–COMMERCIAL USE. ANY
              REPRODUCTION, COUNTERFEITING AND COMMERCIAL TRADE OF THE COUPON IS
              STRICTLY FORBIDDEN, ALONG WITH ANY ILLEGAL ACTIVITY RELATED TO THE
              PURCHASE AND/OR USE OF THE COUPON.
            </p>

            <p className="text-xl font-medium">MISTAKES</p>
            <p className="font-light">
              FROM TIME TO TIME, INFORMATION ON THE SERVICE MAY CONTAIN TYPOS,
              INACCURACIES, OR OMISSIONS WITH RESPECT TO PRICING, SERVICE
              OFFERINGS, PROMOTIONAL OFFERS/COUPONS, AND OTHER MATTERS. WE
              RESERVE THE RIGHT, WITHOUT PRIOR NOTICE, TO CORRECT ANY ERRORS,
              INACCURACIES OR OMISSIONS, TO CHANGE OR UPDATE INFORMATION, AND TO
              REFUSE OR CANCEL ORDERS IF ANY INFORMATION ON THE SERVICES
              CONTAINS A TYPO, INACCURACY, OR OMISSION AT ANY TIME (INCLUDING
              AFTER YOU HAVE SUBMITTED YOUR ORDER AND AFTER YOUR CREDIT CARD OR
              OTHER PAYMENT METHOD HAVE BEEN CHARGED).
            </p>

            <p className="text-xl font-medium">PROPRIETARY RIGHTS</p>
            <p className="font-light">
              MATERIALS WITH RESPECT TO THE SERVICE AND THE PROGRAM, INCLUDING,
              WITHOUT LIMITATION, NAMES, LOGOS, TRADEMARKS, IMAGES, TEXT,
              COLUMNS, GRAPHICS, VIDEOS, PHOTOGRAPHS, ILLUSTRATIONS, ARTWORK,
              SOFTWARE AND OTHER ELEMENTS (COLLECTIVELY, "MATERIAL") ARE
              PROTECTED BY COPYRIGHTS, TRADEMARKS AND/OR OTHER INTELLECTUAL
              PROPERTY RIGHTS OWNED AND CONTROLLED BY Lagree Eliteform OR BY
              THIRD PARTIES THAT HAVE LICENSED OR OTHERWISE PROVIDED THEIR
              MATERIAL TO THE COMPANY. YOU ACKNOWLEDGE AND AGREE THAT ALL
              MATERIALS ON THE SERVICE ARE MADE AVAILABLE TO YOU FOR LIMITED,
              NON-COMMERCIAL, PERSONAL USE ONLY. NO MATERIAL MAY BE COPIED,
              REPRODUCED, REPUBLISHED, SOLD, DOWNLOADED, POSTED, TRANSMITTED, OR
              DISTRIBUTED IN ANY WAY, OR OTHERWISE USED FOR ANY PURPOSE, BY ANY
              PERSON OR ENTITY, WITHOUT THE COMPANY'S PRIOR EXPRESS WRITTEN
              PERMISSION.
            </p>

            <p className="text-xl font-medium">
              CONSENT TO ELECTRONIC COMMUNICATIONS
            </p>
            <p className="font-light">
              BY USING THE SERVICE, YOU CONSENT TO RECEIVING ELECTRONIC
              COMMUNICATIONS FROM US. THESE COMMUNICATIONS MAY INCLUDE NOTICES
              ABOUT YOUR ACCOUNT AND INFORMATION CONCERNING OR RELATED TO THE
              SERVICE. YOU AGREE THAT ANY NOTICES, AGREEMENTS, DISCLOSURES, OR
              OTHER COMMUNICATIONS THAT WE SEND TO YOU ELECTRONICALLY WILL
              SATISFY ANY LEGAL COMMUNICATION REQUIREMENTS, INCLUDING THAT SUCH
              COMMUNICATIONS BE IN WRITING. YOU ARE SOLELY RESPONSIBLE FOR ALL
              FEES CHARGED BY YOUR TELECOMMUNICATIONS SERVICE PROVIDER OR ANY
              OTHER SERVICE PROVIDER RELATED TO YOUR USE OF THE SERVICE,
              INCLUDING WITHOUT LIMITATION ANY SMS / TEXT MESSAGING FEES, DATA
              CHARGES, AND OTHER FEES.
            </p>

            <p className="text-xl font-medium">SUPPLEMENTAL TERMS</p>
            <p className="font-light">
              SUPPLEMENTAL TERMS MAY APPLY TO CERTAIN PROGRAMS OR PROMOTIONS,
              AND SUCH SUPPLEMENTAL TERMS WILL BE DISCLOSED TO YOU IN CONNECTION
              WITH THE APPLICABLE PROGRAMS OR PROMOTIONS. SUPPLEMENTAL TERMS ARE
              IN ADDITION TO, AND SHALL BE DEEMED A PART OF, THESE TERMS FOR THE
              PURPOSES OF THE APPLICABLE PROGRAM OR PROMOTION. SUPPLEMENTAL
              TERMS SHALL PREVAIL OVER THESE TERMS IN THE EVENT OF A CONFLICT.
            </p>

            <p className="text-xl font-medium">CLASS ACTION WAIVER</p>
            <p className="font-light">
              WHERE PERMITTED UNDER APPLICABLE LAW, YOU MAY BRING CLAIMS AGAINST
              Lagree Eliteform ONLY IN YOUR INDIVIDUAL CAPACITY AND NOT AS A
              PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE
              ACTION. YOU AGREE TO WAIVE THE RIGHT TO A TRIAL BY JURY WITH
              RESPECT TO ANY DISPUTES.
            </p>

            <p className="text-xl font-medium">UPDATES TO THESE TERMS</p>
            <p className="font-light">
              WE MAY OCCASIONALLY UPDATE THESE TERMS. WHEN WE DO, WE WILL
              ENDEAVOUR TO REVISE THE "LAST UPDATED" DATE AT THE END OF THESE
              TERMS. TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOUR CONTINUED
              USE OF OUR SERVICE OR PROGRAM AFTER WE MAKE UPDATES TO THESE TERMS
              WILL BE SUBJECT TO THE THEN-CURRENT TERMS.
            </p>

            <p className="text-xl font-medium">PRIVACY POLICY</p>
            <p className="font-light">
              EACH TIME YOU USE OUR SERVICE OR PARTICIPATE IN A PROGRAM, YOU
              CONSENT TO THE COLLECTION, USE AND DISCLOSURE OF PERSONAL
              INFORMATION BY Lagree Eliteform IN ACCORDANCE WITH OUR PRIVACY
              POLICY, AS AMENDED FROM TIME TO TIME.
            </p>

            <p className="text-xl font-medium">
              GOVERNING LAW AND JURISDICTION
            </p>
            <p className="font-light">
              THESE TERMS SHALL BE INTERPRETED AND CONSTRUED IN ACCORDANCE WITH
              THE LAWS OF THE PROVINCE OF BRITISH COLUMBIA AND THE FEDERAL LAWS
              OF CANADA APPLICABLE THEREIN; AND TO THE EXTENT PERMITTED BY
              APPLICABLE LAW, ANY CLAIM OR CAUSE OF ACTION ARISING UNDER THIS
              AGREEMENT MAY BE BROUGHT ONLY IN THE COURTS OF THE PROVINCE OF
              BRITISH COLUMBIA, AND YOU HEREBY CONSENT TO THE EXCLUSIVE
              JURISDICTION OF SUCH COURTS; PROVIDED THAT (I) YOU SHALL BE
              PERMITTED TO BRING A CLAIM IN THE COURTS OF THE PROVINCE OF
              ONTARIO WITH RESPECT TO ANY ACTIVITY IN ONTARIO; AND (II) TO THE
              EXTENT THAT APPLICABLE CONSUMER PROTECTION LAWS OF ANY
              JURISDICTION PERMIT YOU TO BRING A CLAIM IN SUCH OTHER
              JURISDICTION, THEN THIS AGREEMENT SHALL NOT PROHIBIT YOU FROM
              BRINGING A CLAIM IN SUCH JURISDICTION.
            </p>

            <p className="text-xl font-medium">ENGLISH LANGUAGE</p>
            <p className="font-light">
              THE PARTIES HERETO HAVE REQUIRED THAT THIS AGREEMENT AND ALL
              DOCUMENTS AND NOTICES RESULTING FROM IT BE DRAWN UP IN ENGLISH.
              LES PARTIES AUX PRÉSENTS ONT EXIGÉS QUE LA PRÉSENTE CONVENTION
              AINSI QUE TOUS LES DOCUMENTS ET AVIS QUI S'Y RATTACHENT OU QUI EN
              DÉCOULERONT SOIT RÉDIGÉS EN LA LANGUE ANGLAISE.
            </p>

            <p className="text-xl font-medium">CONTACTING Lagree Eliteform</p>
            <p className="font-light">
              FOR QUESTIONS, COMMENTS, COMPLAINTS, OR CLAIMS RELATED TO LAGREE
              WEST LOCATIONS, PLEASE CONTACT US AT{" "}
              <a
                href="mailto:info@lagreeeliteform.com
"
                className="underline"
              >
                {" "}
                info@lagreeeliteform.com
              </a>
              .
            </p>

            <p className="text-lg font-medium"> LAST UPDATED: MARCH 2025</p>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default TermsOfService;
